### ISSUE TITLE
Chassis.ml service behind proxy

### ISSUE THREAD

**Issue by EMorf** [modzy/chassis#103]
We are trying to use a locally deployed Chassis.ml service for our environment. We have followed the instructions here: https://chassis.ml/getting-started/deploy-manual/ to the letter, however we had to edit some configuration files in order to enable HELM and K3S to use the proxy to connect to the internet, as the environment is regulated. 

Up to this point, everything works okay. However, when a chassis-builder-job pod fires up, after trying to interact with the Chassis service, it always errors out. 

**GET https://index.docker.io/v2/ ... No such host** is returned when I check the logs of the builder job pod. I suspect that this has to do with the need of a proxy to reach the internet. However, kaniko is not aware of the proxy which is running on the host machine.

Would it be possible to be able to pass the host environmental variables http_proxy and https_proxy to the kaniko pod when it is created, in order to enable reaching the internet in semi-airgapped environments?

**Comment by DataScienceDeconstructed** [comment]
@EMorf Thanks for bring this to our attention. 
Your use case isn't one we've had to test before, but it's obviously one that needs to be addressed. 
@saumil-d, @bmunday3, and I have brainstormed a couple of ideas and think we have a path forward. 
Most of us that can start fixing this are busy prepping for MLOps World next week, but we'll put it at the top of the heap for corrective action after the conference.
@n8mellis probably going to need your networking expertise on this.

**Comment by DataScienceDeconstructed** [comment]
@EMorf 
OK so we have a branch of Chassis that runs behind a proxy. It can be found here: [https://github.com/modzy/chassis/tree/http_proxy] 

Currently it has only been tested against a Chassis installation behind a proxy in AWS. The branch will not be merged to main until we get it tested with all 6 of the possible new configurations. This may take a couple of weeks because we'll need to tap expertise around the project to setup proxy no proxy combos of AWS, GCP, and standalone.

In the mean time I'll  post a set of instructions for you if you want to try to use the branch for deployment.

**Comment by EMorf** [comment]
After talking to @bmunday3 yesterday, this might be superseded with the next version of Chassis. I'm happy to close this issue for now.
