### ISSUE TITLE
Draft messaging for promotion (partners, social, email)

### ISSUE THREAD

**Issue by caradoxical** [modzy/chassis#38]

**Comment by lukemarsden** [comment]
Here's the meetup talk title & abstract

Title: Building Machine Learning models into Docker images

In this talk, we'll do a deep dive on building ML models into container images so that you can run them in production for inference. There are various questions around doing this: who should build the images and when? What should they contain? How should data science & ML teams interact with DevOps teams? If you build images specific to one platform, will you get locked in? If you try to build your containers inside a container, what happens, and why is this a security challenge?

Based on our experience setting up ML container builds for many clients, we'll propose a set of best practices for ensuring secure, multi-tenant image builds that avoid lock-in, and we'll also share some tooling (chassis.ml) and a standard (openmodel.ml) we propose for doing this.

**Comment by lukemarsden** [comment]
Here's a blurb I created:

We created chassis.ml to help bridge the gap between data scientist/ML teams and DevOps teams. Getting models into production is still one of the main challenges for companies trying to get value out of AI/ML, and DevOps teams could do worse than deploying chassis to their k8s cluster to give data scientists an easy python SDK to convert their MLflow models into runnable, production ready container images that are multi-platform.

While we already support MLflow, kfserving and modzy, we're looking to integrate with other model sources and ML runtimes so come and get involved in #chassis-model-builder on the MLOps community slack.

Demo: https://youtu.be/3i4ynyECo_I
Test drive: https://chassis.ml/#test-drive
